### ISSUE TITLE
Camo Only Effects Previously Bought Projectiles

### ISSUE THREAD

**Issue by JoelCrafter43** [DarkTerraYT/EnhancementMonkey#1]
The camo detection upgrade only allows projectiles bought before buying it to attack camo and it can only be bought once meaning once you buy it you'd have to sell the tower and rebuy it in order to get new camo detecting projectiles

**Comment by DarkTerraYT** [comment]
thought I fixed this, I'll try fixing it

**Comment by DarkTerraYT** [comment]
I fixed it, I'll release the fix when the update's done

**Comment by JoelCrafter43** [comment]
So it seems as though the update that fixed the permanent camo detection issue brought this issue back, not sure if anything can be done about it but I figured it was worth bringing to attention
