### ISSUE TITLE
Camo upgrade persists until game re-opened

### ISSUE THREAD

**Issue by JoelCrafter43** [DarkTerraYT/EnhancementMonkey#2]
So after the update that fixed the camo not applying to new projectiles it now applies to all new projectiles even after restarts and even starting new maps and it requires restarting the game to make the projectiles not have camo detection.
This bug is in opinion preferable to the previous one but I figured it was worth mentioning.

**Comment by DarkTerraYT** [comment]
fixed with 2.0.0
