### ISSUE TITLE
pierce being set to 1 instead of +=1

### ISSUE THREAD

**Issue by ayaOwO** [DarkTerraYT/EnhancementMonkey#4]
Watching ISAB's recent video it seems like the pierce upgrades don't work.

After looking at the pierce upgrades it seems like this line should be
```projectileModel.pierce += 1;```
instead of
```projectileModel.pierce = 1;```

resulting in the pierce being set to 1 instead of adding one

https://github.com/DarkTerraYT/EnhancementMonkey/blob/7e38f379a48b7eb359d3d57e2082a0d37777f679/Api/Enhancements/Normal/Pierce1.cs#L44

**Comment by DarkTerraYT** [comment]
should prolly fix that

**Comment by DarkTerraYT** [comment]
Fixed, will release with next update
