### ISSUE TITLE
crashes when loading the model 

### ISSUE THREAD

**Issue by theultracodex** [DarkTerraYT/EnhancementMonkey#5]
when trying to place the tower down it crashes when the model try's to load

**Comment by LolISkriptIsCool** [comment]
same please fix it

**Comment by quveryFish** [comment]
I have the same problem, i dont know how to fix

**Comment by phain** [comment]
I found the solution a a previous issue, the mod is compatible with MelonLoader version 0.6.1.

Be sure to downgrade MelonLoader from current latest (v0.6.4.), and it should run well

**Comment by LolISkriptIsCool** [comment]
alright thanks

**Comment by DarkTerraYT** [comment]
> I found the solution a a previous issue, the mod is compatible with MelonLoader version 0.6.1.
> 
> Be sure to downgrade MelonLoader from current latest (v0.6.4.), and it should run well

this works
